export const TOGGLE_HAMBURGER = "TOGGLE_HAMBURGER";
export const REQUEST_AUTHORIZATION = "REQUEST_AUTHORIZATION";
export const RECEIVE_AUTHORIZATION = "RECEIVE_AUTHORIZATION";
export const REQUEST_SPEAK_EASIES = "REQUEST_SPEAK_EASIES";
export const RECEIVE_SPEAK_EASIES = "RECEIVE_SPEAK_EASIES";

export const API_URL = "http://localhost:4000";
