export const LOADED_APP = "LOADED_APP";
export const SET_TOKEN = "SET_TOKEN";
export const TOGGLE_HAMBURGER = "TOGGLE_HAMBURGER";

export const REQUEST_AUTHORIZATION = "REQUEST_AUTHORIZATION";
export const RECEIVE_AUTHORIZATION = "RECEIVE_AUTHORIZATION";

export const REQUEST_SPEAK_EASIES = "REQUEST_SPEAK_EASIES";
export const RECEIVE_SPEAK_EASIES = "RECEIVE_SPEAK_EASIES";

export const TAP_SPEAK_EASY = "TAP_SPEAK_EASY";

export const SEND_POST_SPEAK_EASY = "SEND_POST_SPEAK_EASY";
export const RECEIVE_POST_SPEAK_EASY = "RECEIVE_POST_SPEAK_EASY";

export const SEND_UPDATE_SPEAK_EASY = "SEND_UPDATE_SPEAK_EASY";
export const RECEIVE_UPDATE_SPEAK_EASY = "RECEIVE_UPDATE_SPEAK_EASY";

export const API_URL = "http://localhost:4000";
